#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages, let’s install one!

sudo apt update
sudo apt -y install nginx
echo "Hello World!" > /var/www/html/index.html
service nginx start
